import re

SP500_TICKERS = {
    "AAPL": "Apple Inc.",
    "ABBV": "AbbVie Inc.",
    "ABT": "Abbott Laboratories",
    "ACN": "Accenture plc",
    "ADBE": "Adobe Inc.",
    "ADI": "Analog Devices Inc.",
    "ADM": "Archer-Daniels-Midland Co.",
    "ADP": "Automatic Data Processing Inc.",
    "ADSK": "Autodesk Inc.",
    "AEE": "Ameren Corp.",
    "AEP": "American Electric Power Co.",
    "AES": "AES Corp.",
    "AFL": "Aflac Inc.",
    "AIG": "American International Group",
    "AIZ": "Assurant Inc.",
    "AJG": "Arthur J. Gallagher & Co.",
    "AKAM": "Akamai Technologies Inc.",
    "ALB": "Albemarle Corp.",
    "ALGN": "Align Technology Inc.",
    "ALK": "Alaska Air Group Inc.",
    "ALL": "Allstate Corp.",
    "ALLE": "Allegion plc",
    "AMAT": "Applied Materials Inc.",
    "AMCR": "Amcor plc",
    "AMD": "Advanced Micro Devices Inc.",
    "AME": "AMETEK Inc.",
    "AMGN": "Amgen Inc.",
    "AMP": "Ameriprise Financial Inc.",
    "AMT": "American Tower Corp.",
    "AMZN": "Amazon.com Inc.",
    "ANET": "Arista Networks Inc.",
    "ANSS": "ANSYS Inc.",
    "AON": "Aon plc",
    "AOS": "A.O. Smith Corp.",
    "APA": "APA Corp.",
    "APD": "Air Products & Chemicals Inc.",
    "APH": "Amphenol Corp.",
    "APTV": "Aptiv PLC",
    "ARE": "Alexandria Real Estate Equities",
    "ATO": "Atmos Energy Corp.",
    "ATVI": "Activision Blizzard Inc.",
    "AVB": "AvalonBay Communities Inc.",
    "AVGO": "Broadcom Inc.",
    "AVY": "Avery Dennison Corp.",
    "AWK": "American Water Works Co.",
    "AXP": "American Express Co.",
    "AZO": "AutoZone Inc.",
    "BA": "Boeing Co.",
    "BAC": "Bank of America Corp.",
    "BAX": "Baxter International Inc.",
    "BBWI": "Bath & Body Works Inc.",
    "BBY": "Best Buy Co. Inc.",
    "BDX": "Becton Dickinson & Co.",
    "BEN": "Franklin Resources Inc.",
    "BF.B": "Brown-Forman Corp.",
    "BIO": "Bio-Rad Laboratories Inc.",
    "BIIB": "Biogen Inc.",
    "BK": "Bank of New York Mellon Corp.",
    "BKNG": "Booking Holdings Inc.",
    "BKR": "Baker Hughes Co.",
    "BLK": "BlackRock Inc.",
    "BMY": "Bristol-Myers Squibb Co.",
    "BR": "Broadridge Financial Solutions",
    "BRK.B": "Berkshire Hathaway Inc.",
    "BRO": "Brown & Brown Inc.",
    "BSX": "Boston Scientific Corp.",
    "BWA": "BorgWarner Inc.",
    "BXP": "BXP Inc.",
    "CAG": "Conagra Brands Inc.",
    "CAH": "Cardinal Health Inc.",
    "CARR": "Carrier Global Corp.",
    "CAT": "Caterpillar Inc.",
    "CB": "Chubb Limited",
    "CBOE": "Cboe Global Markets Inc.",
    "CBRE": "CBRE Group Inc.",
    "CCI": "Crown Castle Inc.",
    "CCL": "Carnival Corp.",
    "CDAY": "Ceridian HCM Holding Inc.",
    "CDNS": "Cadence Design Systems Inc.",
    "CDW": "CDW Corp.",
    "CE": "Celanese Corp.",
    "CEG": "Constellation Energy Corp.",
    "CF": "CF Industries Holdings Inc.",
    "CFG": "Citizens Financial Group Inc.",
    "CHD": "Church & Dwight Co. Inc.",
    "CHRW": "C.H. Robinson Worldwide Inc.",
    "CHTR": "Charter Communications Inc.",
    "CI": "Cigna Group",
    "CINF": "Cincinnati Financial Corp.",
    "CL": "Colgate-Palmolive Co.",
    "CLX": "Clorox Co.",
    "CMA": "Comerica Inc.",
    "CMCSA": "Comcast Corp.",
    "CME": "CME Group Inc.",
    "CMG": "Chipotle Mexican Grill Inc.",
    "CMI": "Cummins Inc.",
    "CMS": "CMS Energy Corp.",
    "CNC": "Centene Corp.",
    "CNP": "CenterPoint Energy Inc.",
    "COF": "Capital One Financial Corp.",
    "COO": "Cooper Companies Inc.",
    "COP": "ConocoPhillips",
    "COST": "Costco Wholesale Corp.",
    "CPB": "Campbell Soup Co.",
    "CPRT": "Copart Inc.",
    "CPT": "Camden Property Trust",
    "CRL": "Charles River Laboratories",
    "CRM": "Salesforce Inc.",
    "CSCO": "Cisco Systems Inc.",
    "CSGP": "CoStar Group Inc.",
    "CSX": "CSX Corp.",
    "CTAS": "Cintas Corp.",
    "CTLT": "Catalent Inc.",
    "CTRA": "Coterra Energy Inc.",
    "CTSH": "Cognizant Technology Solutions",
    "CTVA": "Corteva Inc.",
    "CVS": "CVS Health Corp.",
    "CVX": "Chevron Corp.",
    "CZR": "Caesars Entertainment Inc.",
    "D": "Dominion Energy Inc.",
    "DAL": "Delta Air Lines Inc.",
    "DD": "DuPont de Nemours Inc.",
    "DE": "Deere & Co.",
    "DECK": "Deckers Outdoor Corp.",
    "DFS": "Discover Financial Services",
    "DG": "Dollar General Corp.",
    "DGX": "Quest Diagnostics Inc.",
    "DHI": "D.R. Horton Inc.",
    "DHR": "Danaher Corp.",
    "DIS": "Walt Disney Co.",
    "DISH": "DISH Network Corp.",
    "DLR": "Digital Realty Trust Inc.",
    "DLTR": "Dollar Tree Inc.",
    "DOV": "Dover Corp.",
    "DOW": "Dow Inc.",
    "DPZ": "Domino's Pizza Inc.",
    "DRI": "Darden Restaurants Inc.",
    "DTE": "DTE Energy Co.",
    "DUK": "Duke Energy Corp.",
    "DVA": "DaVita Inc.",
    "DVN": "Devon Energy Corp.",
    "DXCM": "DexCom Inc.",
    "EA": "Electronic Arts Inc.",
    "EBAY": "eBay Inc.",
    "ECL": "Ecolab Inc.",
    "ED": "Consolidated Edison Inc.",
    "EFX": "Equifax Inc.",
    "EIX": "Edison International",
    "EL": "Estee Lauder Cos. Inc.",
    "EMN": "Eastman Chemical Co.",
    "EMR": "Emerson Electric Co.",
    "ENPH": "Enphase Energy Inc.",
    "EOG": "EOG Resources Inc.",
    "EPAM": "EPAM Systems Inc.",
    "EQIX": "Equinix Inc.",
    "EQR": "Equity Residential",
    "EQT": "EQT Corp.",
    "ES": "Eversource Energy",
    "ESS": "Essex Property Trust Inc.",
    "ETN": "Eaton Corp. plc",
    "ETR": "Entergy Corp.",
    "ETSY": "Etsy Inc.",
    "EVRG": "Evergy Inc.",
    "EW": "Edwards Lifesciences Corp.",
    "EXC": "Exelon Corp.",
    "EXPD": "Expeditors International",
    "EXPE": "Expedia Group Inc.",
    "EXR": "Extra Space Storage Inc.",
    "F": "Ford Motor Co.",
    "FANG": "Diamondback Energy Inc.",
    "FAST": "Fastenal Co.",
    "FBHS": "Fortune Brands Home & Security",
    "FCX": "Freeport-McMoRan Inc.",
    "FDS": "FactSet Research Systems Inc.",
    "FDX": "FedEx Corp.",
    "FE": "FirstEnergy Corp.",
    "FFIV": "F5 Inc.",
    "FIS": "Fidelity National Info Services",
    "FISV": "Fiserv Inc.",
    "FITB": "Fifth Third Bancorp",
    "FLT": "Fleetcor Technologies Inc.",
    "FMC": "FMC Corp.",
    "FOX": "Fox Corp. Class B",
    "FOXA": "Fox Corp. Class A",
    "FRC": "First Republic Bank",
    "FRT": "Federal Realty Investment Trust",
    "FSLR": "First Solar Inc.",
    "FTNT": "Fortinet Inc.",
    "FTV": "Fortive Corp.",
    "GD": "General Dynamics Corp.",
    "GE": "General Electric Co.",
    "GILD": "Gilead Sciences Inc.",
    "GIS": "General Mills Inc.",
    "GL": "Globe Life Inc.",
    "GLW": "Corning Inc.",
    "GM": "General Motors Co.",
    "GNRC": "Generac Holdings Inc.",
    "GOOG": "Alphabet Inc. Class C",
    "GOOGL": "Alphabet Inc. Class A",
    "GPC": "Genuine Parts Co.",
    "GPN": "Global Payments Inc.",
    "GRMN": "Garmin Ltd.",
    "GS": "Goldman Sachs Group Inc.",
    "GWW": "W.W. Grainger Inc.",
    "HAL": "Halliburton Co.",
    "HAS": "Hasbro Inc.",
    "HBAN": "Huntington Bancshares Inc.",
    "HCA": "HCA Healthcare Inc.",
    "HD": "Home Depot Inc.",
    "PEAK": "Healthpeak Properties Inc.",
    "HES": "Hess Corp.",
    "HIG": "Hartford Financial Services",
    "HII": "Huntington Ingalls Industries",
    "HLT": "Hilton Worldwide Holdings Inc.",
    "HOLX": "Hologic Inc.",
    "HON": "Honeywell International Inc.",
    "HPE": "Hewlett Packard Enterprise Co.",
    "HPQ": "HP Inc.",
    "HRL": "Hormel Foods Corp.",
    "HSIC": "Henry Schein Inc.",
    "HST": "Host Hotels & Resorts Inc.",
    "HSY": "Hershey Co.",
    "HUBB": "Hubbell Inc.",
    "HUM": "Humana Inc.",
    "HWM": "Howmet Aerospace Inc.",
    "IBM": "International Business Machines",
    "ICE": "Intercontinental Exchange Inc.",
    "IDXX": "IDEXX Laboratories Inc.",
    "IEX": "IDEX Corp.",
    "IFF": "International Flavors & Fragrances",
    "ILMN": "Illumina Inc.",
    "INCY": "Incyte Corp.",
    "INTC": "Intel Corp.",
    "INTU": "Intuit Inc.",
    "INVH": "Invitation Homes Inc.",
    "IP": "International Paper Co.",
    "IPG": "Interpublic Group of Cos.",
    "IQV": "IQVIA Holdings Inc.",
    "IR": "Ingersoll Rand Inc.",
    "IRM": "Iron Mountain Inc.",
    "ISRG": "Intuitive Surgical Inc.",
    "IT": "Gartner Inc.",
    "ITW": "Illinois Tool Works Inc.",
    "IVZ": "Invesco Ltd.",
    "J": "Jacobs Solutions Inc.",
    "JBHT": "J.B. Hunt Transport Services",
    "JCI": "Johnson Controls International",
    "JKHY": "Jack Henry & Associates Inc.",
    "JNJ": "Johnson & Johnson",
    "JNPR": "Juniper Networks Inc.",
    "JPM": "JPMorgan Chase & Co.",
    "K": "Kellanova",
    "KDP": "Keurig Dr Pepper Inc.",
    "KEY": "KeyCorp",
    "KEYS": "Keysight Technologies Inc.",
    "KHC": "Kraft Heinz Co.",
    "KIM": "Kimco Realty Corp.",
    "KLAC": "KLA Corp.",
    "KMB": "Kimberly-Clark Corp.",
    "KMI": "Kinder Morgan Inc.",
    "KMX": "CarMax Inc.",
    "KO": "Coca-Cola Co.",
    "KR": "Kroger Co.",
    "L": "Loews Corp.",
    "LDOS": "Leidos Holdings Inc.",
    "LEN": "Lennar Corp.",
    "LH": "Labcorp Holdings Inc.",
    "LHX": "L3Harris Technologies Inc.",
    "LIN": "Linde plc",
    "LKQ": "LKQ Corp.",
    "LLY": "Eli Lilly & Co.",
    "LMT": "Lockheed Martin Corp.",
    "LNT": "Alliant Energy Corp.",
    "LOW": "Lowe's Cos. Inc.",
    "LRCX": "Lam Research Corp.",
    "LUMN": "Lumen Technologies Inc.",
    "LUV": "Southwest Airlines Co.",
    "LVS": "Las Vegas Sands Corp.",
    "LW": "Lamb Weston Holdings Inc.",
    "LYB": "LyondellBasell Industries",
    "LYV": "Live Nation Entertainment Inc.",
    "MA": "Mastercard Inc.",
    "MAA": "Mid-America Apartment Communities",
    "MAR": "Marriott International Inc.",
    "MAS": "Masco Corp.",
    "MCD": "McDonald's Corp.",
    "MCHP": "Microchip Technology Inc.",
    "MCK": "McKesson Corp.",
    "MCO": "Moody's Corp.",
    "MDLZ": "Mondelez International Inc.",
    "MDT": "Medtronic plc",
    "MET": "MetLife Inc.",
    "META": "Meta Platforms Inc.",
    "MGM": "MGM Resorts International",
    "MHK": "Mohawk Industries Inc.",
    "MKC": "McCormick & Co. Inc.",
    "MKTX": "MarketAxess Holdings Inc.",
    "MLM": "Martin Marietta Materials Inc.",
    "MMC": "Marsh & McLennan Cos. Inc.",
    "MMM": "3M Co.",
    "MNST": "Monster Beverage Corp.",
    "MO": "Altria Group Inc.",
    "MOH": "Molina Healthcare Inc.",
    "MOS": "Mosaic Co.",
    "MPC": "Marathon Petroleum Corp.",
    "MPWR": "Monolithic Power Systems Inc.",
    "MRK": "Merck & Co. Inc.",
    "MRNA": "Moderna Inc.",
    "MRO": "Marathon Oil Corp.",
    "MS": "Morgan Stanley",
    "MSCI": "MSCI Inc.",
    "MSFT": "Microsoft Corp.",
    "MSI": "Motorola Solutions Inc.",
    "MTB": "M&T Bank Corp.",
    "MTCH": "Match Group Inc.",
    "MTD": "Mettler-Toledo International",
    "MU": "Micron Technology Inc.",
    "NCLH": "Norwegian Cruise Line Holdings",
    "NDAQ": "Nasdaq Inc.",
    "NDSN": "Nordson Corp.",
    "NEE": "NextEra Energy Inc.",
    "NEM": "Newmont Corp.",
    "NFLX": "Netflix Inc.",
    "NI": "NiSource Inc.",
    "NKE": "NIKE Inc.",
    "NOC": "Northrop Grumman Corp.",
    "NOW": "ServiceNow Inc.",
    "NRG": "NRG Energy Inc.",
    "NSC": "Norfolk Southern Corp.",
    "NTAP": "NetApp Inc.",
    "NTRS": "Northern Trust Corp.",
    "NUE": "Nucor Corp.",
    "NVDA": "NVIDIA Corp.",
    "NVR": "NVR Inc.",
    "NWL": "Newell Brands Inc.",
    "NWS": "News Corp. Class B",
    "NWSA": "News Corp. Class A",
    "NXPI": "NXP Semiconductors NV",
    "O": "Realty Income Corp.",
    "ODFL": "Old Dominion Freight Line Inc.",
    "OGN": "Organon & Co.",
    "OKE": "ONEOK Inc.",
    "OMC": "Omnicom Group Inc.",
    "ON": "ON Semiconductor Corp.",
    "ORCL": "Oracle Corp.",
    "ORLY": "O'Reilly Automotive Inc.",
    "OTIS": "Otis Worldwide Corp.",
    "OXY": "Occidental Petroleum Corp.",
    "PARA": "Paramount Global",
    "PAYC": "Paycom Software Inc.",
    "PAYX": "Paychex Inc.",
    "PCAR": "PACCAR Inc.",
    "PCG": "PG&E Corp.",
    "PEAK": "Healthpeak Properties Inc.",
    "PEG": "Public Service Enterprise Group",
    "PEP": "PepsiCo Inc.",
    "PFE": "Pfizer Inc.",
    "PFG": "Principal Financial Group Inc.",
    "PG": "Procter & Gamble Co.",
    "PGR": "Progressive Corp.",
    "PH": "Parker-Hannifin Corp.",
    "PHM": "PulteGroup Inc.",
    "PKG": "Packaging Corp. of America",
    "PKI": "PerkinElmer Inc.",
    "PLD": "Prologis Inc.",
    "PM": "Philip Morris International Inc.",
    "PNC": "PNC Financial Services Group",
    "PNR": "Pentair plc",
    "PNW": "Pinnacle West Capital Corp.",
    "POOL": "Pool Corp.",
    "PPG": "PPG Industries Inc.",
    "PPL": "PPL Corp.",
    "PRU": "Prudential Financial Inc.",
    "PSA": "Public Storage",
    "PSX": "Phillips 66",
    "PTC": "PTC Inc.",
    "PVH": "PVH Corp.",
    "PWR": "Quanta Services Inc.",
    "PXD": "Pioneer Natural Resources Co.",
    "PYPL": "PayPal Holdings Inc.",
    "QCOM": "Qualcomm Inc.",
    "QRVO": "Qorvo Inc.",
    "RCL": "Royal Caribbean Cruises Ltd.",
    "RE": "Everest Re Group Ltd.",
    "REG": "Regency Centers Corp.",
    "REGN": "Regeneron Pharmaceuticals Inc.",
    "RF": "Regions Financial Corp.",
    "RHI": "Robert Half International Inc.",
    "RJF": "Raymond James Financial Inc.",
    "RL": "Ralph Lauren Corp.",
    "RMD": "ResMed Inc.",
    "ROK": "Rockwell Automation Inc.",
    "ROL": "Rollins Inc.",
    "ROP": "Roper Technologies Inc.",
    "ROST": "Ross Stores Inc.",
    "RSG": "Republic Services Inc.",
    "RTX": "RTX Corp.",
    "SBAC": "SBA Communications Corp.",
    "SBNY": "Signature Bank",
    "SBUX": "Starbucks Corp.",
    "SCHW": "Charles Schwab Corp.",
    "SEE": "Sealed Air Corp.",
    "SHW": "Sherwin-Williams Co.",
    "SIVB": "SVB Financial Group",
    "SJM": "J.M. Smucker Co.",
    "SLB": "Schlumberger NV",
    "SNA": "Snap-on Inc.",
    "SNPS": "Synopsys Inc.",
    "SO": "Southern Co.",
    "SPG": "Simon Property Group Inc.",
    "SPGI": "S&P Global Inc.",
    "SRE": "Sempra Energy",
    "STE": "STERIS plc",
    "STT": "State Street Corp.",
    "STX": "Seagate Technology Holdings plc",
    "STZ": "Constellation Brands Inc.",
    "SWK": "Stanley Black & Decker Inc.",
    "SWKS": "Skyworks Solutions Inc.",
    "SYF": "Synchrony Financial",
    "SYK": "Stryker Corp.",
    "SYY": "Sysco Corp.",
    "T": "AT&T Inc.",
    "TAP": "Molson Coors Beverage Co.",
    "TDG": "TransDigm Group Inc.",
    "TDY": "Teledyne Technologies Inc.",
    "TECH": "Bio-Techne Corp.",
    "TEL": "TE Connectivity Ltd.",
    "TER": "Teradyne Inc.",
    "TFC": "Truist Financial Corp.",
    "TFX": "Teleflex Inc.",
    "TGT": "Target Corp.",
    "TJX": "TJX Cos. Inc.",
    "TMO": "Thermo Fisher Scientific Inc.",
    "TMUS": "T-Mobile US Inc.",
    "TPR": "Tapestry Inc.",
    "TRGP": "Targa Resources Corp.",
    "TRMB": "Trimble Inc.",
    "TROW": "T. Rowe Price Group Inc.",
    "TRV": "Travelers Cos. Inc.",
    "TSCO": "Tractor Supply Co.",
    "TSLA": "Tesla Inc.",
    "TSN": "Tyson Foods Inc.",
    "TT": "Trane Technologies plc",
    "TTWO": "Take-Two Interactive Software",
    "TXN": "Texas Instruments Inc.",
    "TXT": "Textron Inc.",
    "TYL": "Tyler Technologies Inc.",
    "UAL": "United Airlines Holdings Inc.",
    "UDR": "UDR Inc.",
    "UHS": "Universal Health Services Inc.",
    "ULTA": "Ulta Beauty Inc.",
    "UNH": "UnitedHealth Group Inc.",
    "UNP": "Union Pacific Corp.",
    "UPS": "United Parcel Service Inc.",
    "URI": "United Rentals Inc.",
    "USB": "U.S. Bancorp",
    "V": "Visa Inc.",
    "VFC": "V.F. Corp.",
    "VICI": "VICI Properties Inc.",
    "VLO": "Valero Energy Corp.",
    "VMC": "Vulcan Materials Co.",
    "VRSK": "Verisk Analytics Inc.",
    "VRSN": "VeriSign Inc.",
    "VRTX": "Vertex Pharmaceuticals Inc.",
    "VTR": "Ventas Inc.",
    "VTRS": "Viatris Inc.",
    "VZ": "Verizon Communications Inc.",
    "WAB": "Westinghouse Air Brake Technologies",
    "WAT": "Waters Corp.",
    "WBA": "Walgreens Boots Alliance Inc.",
    "WBD": "Warner Bros. Discovery Inc.",
    "WDC": "Western Digital Corp.",
    "WEC": "WEC Energy Group Inc.",
    "WELL": "Welltower Inc.",
    "WFC": "Wells Fargo & Co.",
    "WHR": "Whirlpool Corp.",
    "WM": "Waste Management Inc.",
    "WMB": "Williams Cos. Inc.",
    "WMT": "Walmart Inc.",
    "WRB": "W.R. Berkley Corp.",
    "WRK": "WestRock Co.",
    "WST": "West Pharmaceutical Services",
    "WTW": "Willis Towers Watson plc",
    "WY": "Weyerhaeuser Co.",
    "WYNN": "Wynn Resorts Ltd.",
    "XEL": "Xcel Energy Inc.",
    "XOM": "Exxon Mobil Corp.",
    "XRAY": "DENTSPLY SIRONA Inc.",
    "XYL": "Xylem Inc.",
    "YUM": "Yum! Brands Inc.",
    "ZBH": "Zimmer Biomet Holdings Inc.",
    "ZBRA": "Zebra Technologies Corp.",
    "ZION": "Zions Bancorporation",
    "ZTS": "Zoetis Inc.",
    # Popular non-S&P 500 tickers commonly discussed on Reddit
    "GME": "GameStop Corp.",
    "AMC": "AMC Entertainment Holdings",
    "PLTR": "Palantir Technologies Inc.",
    "SOFI": "SoFi Technologies Inc.",
    "RIVN": "Rivian Automotive Inc.",
    "LCID": "Lucid Group Inc.",
    "NIO": "NIO Inc.",
    "BABA": "Alibaba Group Holding Ltd.",
    "SHOP": "Shopify Inc.",
    "SQ": "Block Inc.",
    "SNAP": "Snap Inc.",
    "PINS": "Pinterest Inc.",
    "RBLX": "Roblox Corp.",
    "COIN": "Coinbase Global Inc.",
    "HOOD": "Robinhood Markets Inc.",
    "MARA": "Marathon Digital Holdings Inc.",
    "RIOT": "Riot Platforms Inc.",
    "DKNG": "DraftKings Inc.",
    "ROKU": "Roku Inc.",
    "PATH": "UiPath Inc.",
    "U": "Unity Software Inc.",
    "CRWD": "CrowdStrike Holdings Inc.",
    "SNOW": "Snowflake Inc.",
    "NET": "Cloudflare Inc.",
    "DDOG": "Datadog Inc.",
    "ZS": "Zscaler Inc.",
    "PANW": "Palo Alto Networks Inc.",
    "ARM": "Arm Holdings plc",
    "SMCI": "Super Micro Computer Inc.",
    "MSTR": "MicroStrategy Inc.",
    "AI": "C3.ai Inc.",
    "IONQ": "IonQ Inc.",
    "RGTI": "Rigetti Computing Inc.",
    "WOLF": "Wolfspeed Inc.",
    "SOUN": "SoundHound AI Inc.",
    "BBAI": "BigBear.ai Holdings Inc.",
}

# Words that look like tickers but aren't
COMMON_WORDS = {
    "A", "I", "AM", "AN", "AS", "AT", "BE", "BY", "DO", "GO", "HE", "IF",
    "IN", "IS", "IT", "ME", "MY", "NO", "OF", "OK", "ON", "OR", "OUR",
    "SO", "TO", "UP", "US", "WE", "CEO", "CFO", "CTO", "COO", "IPO",
    "ETF", "GDP", "SEC", "FBI", "CIA", "FDA", "FED", "IMO", "IMHO",
    "FYI", "TBH", "LOL", "OMG", "WTF", "IDK", "FOMO", "YOLO", "HODL",
    "DD", "TA", "PT", "EPS", "ATH", "ATL", "OTM", "ITM", "IV",
    "PE", "PB", "PS", "RSI", "MACD", "SMA", "EMA", "VWAP",
    "USA", "UK", "EU", "UN", "WHO", "CDC", "NIH", "IRS",
    "THE", "AND", "FOR", "ARE", "BUT", "NOT", "YOU", "ALL",
    "CAN", "HER", "WAS", "ONE", "HAS", "HIS", "HOW", "MAN",
    "NEW", "NOW", "OLD", "SEE", "WAY", "MAY", "DAY", "TOO",
    "ANY", "TOP", "RUN", "WIN", "BIG", "RED", "TEN", "OWN",
    "SAY", "SHE", "HIM", "HIS", "GET", "OUT", "CUT", "PUT",
    "SET", "ADD", "END", "DID", "LET", "RAN", "GOT", "HAD",
    "YEA", "YEP", "NAH", "NVM", "SMH", "IRL", "IIRC",
    "TLDR", "DM", "PM", "EDIT", "OG", "PSA", "NSFW",
    "BULL", "BEAR", "LONG", "SHORT", "BUY", "SELL", "HOLD",
    "CALL", "PUTS", "PUMP", "DUMP", "DIP", "RIP", "MOON",
    "APE", "APES", "BANG", "BAGS", "GAIN", "LOSS", "YEET",
}

# Cashtag pattern: $AAPL, $TSLA
CASHTAG_PATTERN = re.compile(r'\$([A-Z]{1,5})\b')

# Bare uppercase pattern: AAPL, TSLA (2-5 letters to reduce noise)
BARE_TICKER_PATTERN = re.compile(r'\b([A-Z]{2,5})\b')


def extract_tickers(text: str) -> list[str]:
    if not text:
        return []

    found = set()

    # Cashtag mentions always get added if they're valid tickers
    for match in CASHTAG_PATTERN.finditer(text):
        ticker = match.group(1)
        if ticker in SP500_TICKERS:
            found.add(ticker)

    # Bare uppercase words -- only if in ticker list AND not a common word
    for match in BARE_TICKER_PATTERN.finditer(text):
        word = match.group(1)
        if word in SP500_TICKERS and word not in COMMON_WORDS:
            found.add(word)

    return sorted(found)


def is_valid_ticker(ticker: str) -> bool:
    return ticker.upper() in SP500_TICKERS


def get_company_name(ticker: str) -> str:
    return SP500_TICKERS.get(ticker.upper(), ticker.upper())


def search_tickers(query: str, limit: int = 10) -> list[dict]:
    query = query.upper().strip()
    if not query:
        return []

    results = []
    for ticker, name in SP500_TICKERS.items():
        if ticker.startswith(query) or query in name.upper():
            results.append({"ticker": ticker, "name": name})
            if len(results) >= limit:
                break

    return results
